[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://lineup-backend-xxak.onrender.com"
  # Force rebuild 2025-01-27 