services:
  - type: web
    name: lineup-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # ⚠️ À configurer manuellement dans Render Dashboard
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false  # ⚠️ À configurer manuellement
      - key: CORS_ORIGIN
        value: https://ligneup.netlify.app
    autoDeploy: true
    branch: main
    healthCheckTimeout: 300
    numInstances: 1
    minInstances: 1
    maxInstances: 1 